---
title: O Modo de Espera a Frio gera o erro "O registro DataStoreException não existe"
description: Descrição
solution: Experience Manager
product: Experience Manager
applies-to: Experience Manager
keywords: KCS, AEM, standby frio, DataStoreException, Adobe Experience Manager, o registro não existe, erro, aviso, aviso
resolution: Resolution
internal-notes: https://issues.apache.org/jira/browse/OAK-8202,https://jira.corp.adobe.com/browse/GRANITE-11668
bug: false
article-created-by: Jim Menn
article-created-date: 9/28/2022 2:23:47 PM
article-published-by: Jim Menn
article-published-date: 9/28/2022 5:41:23 PM
version-number: 3
article-number: KA-15610
dynamics-url: https://adobe-ent.crm.dynamics.com/main.aspx?forceUCI=1&pagetype=entityrecord&etn=knowledgearticle&id=5e521024-393f-ed11-9db1-0022480866ad
exl-id: d37d0338-be4f-4660-a4b2-cd1179717e07
source-git-commit: 4702b69f883128bf305ec64f012ef01903f3f582
workflow-type: tm+mt
source-wordcount: '231'
ht-degree: 1%

---

# O Modo de Espera a Frio gera o erro &quot;O registro DataStoreException não existe&quot;

## Descrição


<b>Ambiente</b>
Adobe Experience Manager

<b>Problema</b>
O Modo de espera forçado com o Armazenamento de dados de arquivo dedicado lança um aviso sobre a ID de blob ausente semelhante ao erro aqui:


```
*WARN* standby-run-1 org.apache.jackrabbit.oak.plugins.blob.datastore.DataStoreBlobStore Error occurred while loading bytes from steam while fetching for id f68a92b34779bbd194184251ec916370f3ebd301d6e32a8980aad070d57a1845#25522

java.util.concurrent.ExecutionException: java.io.IOException: org.apache.jackrabbit.core.data.DataStoreException: Record f68a92b34779bbd194184251ec916370f3ebd301d6e32a8980aad070d57a1845 does not exist

    at org.apache.jackrabbit.oak.cache.CacheLIRS$Segment.load(CacheLIRS.java:1017) org.apache.jackrabbit.oak-core-spi:1.10.3

...

Caused by: org.apache.jackrabbit.core.data.DataStoreException: Record cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20 does not exist

    at org.apache.jackrabbit.core.data.AbstractDataStore.getRecord(AbstractDataStore.java:59)
```


<b>Causa</b>
Isso é apenas um aviso, não um erro.

Ela vem do fato de que o Armazenamento de dados de arquivos não tem como verificar se um binário existe localmente, exceto tentando carregar a ID do blob.
Se a ID for carregada, os logs não mostrarão esse aviso.
No entanto, se não for encontrado, o standby saberá que precisa sincronizá-lo, portanto, é por isso que você vê esse tipo de aviso nos logs.


## Resolução


<b>Solução</b>
Está funcionando conforme o projetado e não indica um problema com o armazenamento de dados de arquivos.

Para confirmar que a ID do blob não está realmente ausente, siga estas etapas:

1. Por exemplo, use a ID de blob de amostra exibida como ausente nos logs (por exemplo: `cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`).
2. Para essa ID de blob neste exemplo, o endereço do sistema de arquivos deve ser: `ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`.
3. Pesquise o sistema de arquivos na instância stand-by e verifique se o arquivo nomeado está presente no Armazenamento de Dados do Arquivo.
4. Dentro de `/repository/datastore`, use o `list` (Por exemplo: `ls -ald`): `ls -ald ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`.
5. Você deve conseguir ver o arquivo e confirmar que a ID do blob não está realmente ausente.
